const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./endpoints.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                father: "Simon Doe",
                mother: "Marie Doe"
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        Vehicle: {
            Name: "Jhon Doe",
            VehicleType: "Car",
            VehicleName: "Mercedes",
            RegistrationNumber: "ABC1234",
            about: ""
        },
        Device:
        {
            Name: "Jhon Doe",
            DeviceName: "Philips",
            DeviceType: "Light",
            DeviceID: "XYZ",
            about: ""
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            $father: "Simon Doe",
            $mother: "Marie Doe",
            about: ""
        },
        AddVehicle: {
            $name: "Jhon Doe",
            $vehicletype: "Car",
            $vehiclename: "Mercedes",
            $registrationnumber: "ABC1234",
            about: ""
        },
        AddDevice: {
            $name: "Jhon Doe",
            $devicename: "Philips",
            $devicetype: "Light",
            $deviceid: "XYZ",
            about: ""
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})